<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue'
import {request} from '../api'
const items=ref([]),quality=ref(null),impact=ref(null),changeResult=ref(null),error=ref('')
const form=reactive({ciCode:'CI-'+Date.now(),ciType:'APPLICATION',name:'',organizationCode:'ZH-SH',owner:'平台组',criticality:'HIGH',serviceCode:'SVC-CORE',environment:'PROD',lastDiscoveredAt:new Date().toISOString().slice(0,19)})
const relation=reactive({sourceCiCode:'',targetCiCode:'',relationType:'DEPENDS_ON',critical:true})
const change=reactive({ciCodes:[],maxDepth:6,changeTicket:'CHG-2026-'+String(Date.now()).slice(-6),maintenanceWindowApproved:false,emergencyApproved:false})
async function load(){try{[items.value,quality.value]=await Promise.all([request('/api/cmdb/configuration-items'),request('/api/cmdb/quality')])}catch(e){error.value=e.message}}
async function create(){try{await request('/api/cmdb/configuration-items',{method:'POST',body:JSON.stringify(form)});form.ciCode='CI-'+Date.now();form.name='';await load()}catch(e){error.value=e.message}}
async function relate(){try{await request('/api/cmdb/relations',{method:'POST',body:JSON.stringify(relation)});await analyze(relation.targetCiCode);await load()}catch(e){error.value=e.message}}
async function analyze(code){try{impact.value=await request('/api/cmdb/impact/'+encodeURIComponent(code)+'?maxDepth=6')}catch(e){error.value=e.message}}
async function assess(){try{changeResult.value=await request('/api/cmdb/change-impact',{method:'POST',body:JSON.stringify(change)})}catch(e){error.value=e.message}}
async function retire(code){if(!confirm('确认退役配置项 '+code+'？'))return;try{await request('/api/cmdb/configuration-items/'+encodeURIComponent(code)+'/retire',{method:'POST'});await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="head"><div><span>CONFIGURATION GRAPH</span><h3>配置项与服务影响工作台</h3><p>登记可信配置项、建立依赖图，面向生产变更执行多层影响传播和数据质量治理。</p></div><b>关系图实时计算</b></section>
<p v-if="error" class="error" @click="error=''">{{error}} ×</p>
<section v-if="quality" class="metrics"><article><span>配置项</span><b>{{quality.itemCount}}</b></article><article><span>依赖关系</span><b>{{quality.relationCount}}</b></article><article><span>孤立项</span><b>{{quality.orphanCount}}</b></article><article><span>30天未发现</span><b>{{quality.staleCount}}</b></article></section>
<section class="layout"><form class="card" @submit.prevent="create"><h4>登记配置项</h4><div class="form"><label>配置编码<input v-model="form.ciCode" required></label><label>类型<select v-model="form.ciType"><option>APPLICATION</option><option>DATABASE</option><option>SERVER</option><option>MIDDLEWARE</option><option>CLOUD_RESOURCE</option></select></label><label class="wide">名称<input v-model="form.name" required></label><label>组织<input v-model="form.organizationCode" required></label><label>责任人<input v-model="form.owner" required></label><label>关键等级<select v-model="form.criticality"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>环境<select v-model="form.environment"><option>PROD</option><option>STAGING</option><option>TEST</option></select></label><label>业务服务<input v-model="form.serviceCode"></label><label>发现时间<input v-model="form.lastDiscoveredAt" type="datetime-local"></label></div><button>保存配置项</button></form>
<form class="card" @submit.prevent="relate"><h4>建立依赖关系</h4><label>依赖方<select v-model="relation.sourceCiCode" required><option value="">请选择</option><option v-for="i in items" :value="i.ciCode">{{i.ciCode}} · {{i.name}}</option></select></label><label>被依赖方<select v-model="relation.targetCiCode" required><option value="">请选择</option><option v-for="i in items" :value="i.ciCode">{{i.ciCode}} · {{i.name}}</option></select></label><label>关系类型<select v-model="relation.relationType"><option>DEPENDS_ON</option><option>DEPLOYED_ON</option><option>CONNECTS_TO</option><option>MEMBER_OF</option></select></label><label class="check"><input v-model="relation.critical" type="checkbox">关键依赖</label><button>保存关系并分析</button><div v-if="impact" class="impact"><b>影响等级 {{impact.riskLevel}}</b><span>受影响 {{impact.affectedCount}} 项 · 关键链路 {{impact.criticalLinks}}</span><small v-for="i in impact.affectedItems">{{i.ciCode}} / 第 {{i.depth}} 层</small></div></form></section>
<form class="card change" @submit.prevent="assess"><h4>生产变更影响评估</h4><label>变更配置项（可多选）<select v-model="change.ciCodes" multiple required><option v-for="i in items" :value="i.ciCode">{{i.ciCode}} · {{i.name}}</option></select></label><label>变更单号<input v-model="change.changeTicket" pattern="CHG-[A-Z0-9-]{4,40}" required></label><label class="check"><input v-model="change.maintenanceWindowApproved" type="checkbox">维护窗口已批准</label><label class="check"><input v-model="change.emergencyApproved" type="checkbox">紧急变更已放行</label><button>执行变更评估</button><div v-if="changeResult" class="impact"><b>决策 {{changeResult.decision}}</b><span>直接变更 {{changeResult.changedCount}} 项 · 影响 {{changeResult.affectedCount}} 项</span><small v-for="b in changeResult.blockers">阻断：{{b}}</small></div></form>
<section class="card table"><table><thead><tr><th>配置项</th><th>类型 / 环境</th><th>组织 / 负责人</th><th>业务服务</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="i in items"><td><b>{{i.name}}</b><small>{{i.ciCode}}</small></td><td>{{i.ciType}}<small>{{i.environment}} · {{i.criticality}}</small></td><td>{{i.organizationCode}}<small>{{i.owner}}</small></td><td>{{i.serviceCode||'-'}}</td><td>{{i.status}}</td><td><button class="text" @click="analyze(i.ciCode)">影响分析</button><button v-if="i.status==='ACTIVE'" class="text danger" @click="retire(i.ciCode)">退役</button></td></tr></tbody></table></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;background:#fff;border:1px solid #dce2df;padding:24px 28px;margin-bottom:16px}.head span{font-size:11px;letter-spacing:.16em;color:#b47c2f}.head h3{font-size:24px;margin:5px 0}.head p{margin:0;color:#68777c}.head>b{color:#235a74}.metrics{margin-bottom:16px}.layout{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}.card{background:#fff;border:1px solid #dce2df;padding:20px;margin-bottom:16px}.card h4{margin:0 0 16px}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card label{display:grid;gap:5px;font-size:12px;color:#68777c;margin-bottom:10px}.wide{grid-column:1/-1}.card input,.card select{border:1px solid #ccd6d2;padding:9px}.card>button,.card form+button{border:0;background:#235a74;color:#fff;padding:10px 14px;font-weight:700}.check{display:flex!important;grid-template-columns:20px 1fr!important;align-items:center}.impact{display:grid;gap:5px;margin-top:14px;padding:14px;background:#f2f6f5}.impact span,.impact small,td small{display:block;color:#68777c}.change{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:14px;align-items:end}.change select[multiple]{min-height:76px}.table{padding:0;overflow:auto}.table table{min-width:820px}.text{border:0;background:transparent;color:#235a74;padding:4px}.danger{color:#a03f38}.error{color:#a03f38}@media(max-width:900px){.layout,.change{grid-template-columns:1fr}.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
